version: "3.9"

services:
  app:
    build:
      context: .
    restart: always
    volumes:
      - static-data:/vol/web
    env_file:
      - .env-docker
    depends_on:
      - db

  db:
    image: postgres:17-alpine
    restart: always
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    env_file:
      - .env-docker

  proxy:
    build:
      context: ./proxy
    restart: always
    depends_on:
      - app
    ports:
      - "80:8000"
    volumes:
      - static-data:/vol/static


volumes:
  dev-db-data:
  static-data: