services:
  # db:
  #   image: postgres:17
  #   environment:
  #     POSTGRES_DB: ${DATABASE_NAME}
  #     POSTGRES_USER: ${DATABASE_USERNAME}
  #     POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
  #   ports:
  #     - "15432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   env_file:
  #     - .env

  django-web:
    build: .
    container_name: django-docker
    ports:
      - "8000:8000"
    #   depends_on:
    #     - db
    env_file:
      - .env-docker
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

#volumes:
#   postgres_data: